apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app_name }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app_name }}
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Values.app_name }}
          image: {{ .Values.app_image }}
          # Update your config as necessary for your app!          
          ports:
            - containerPort: 3000 
