apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-nginx-svc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}-nginx-svc
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}-nginx