apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-nginx
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}-nginx
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
       app.kubernetes.io/name: {{ .Values.app_name }}-nginx
       app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app_name }}-nginx
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Values.app_name }}-nginx
          image: nginx:alpine
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true              
          ports:
            - containerPort: 80 
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app_name }}-nginx-config