apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-saml-proxy
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}-saml-proxy
    app.kubernetes.io/component: server
spec:
  replicas: 1  
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app_name }}-saml-proxy
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app_name }}-saml-proxy
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: {{ .Values.app_name }}-saml-proxy
          image: {{ .Values.saml_proxy_image }}
          volumeMounts:
            - name: config-volume
              mountPath: /code/app/saml/settings.json
              subPath: settings.json
            - mountPath: /code/app/saml/certs
              name: certificate-volume
              readOnly: true
          ports:
            - containerPort: 3000 
          env:
            # Mongo settings You might want to update this
            - {
                name: MONGOUSER,
                valueFrom: { secretKeyRef: { name: {{ .Values.app_name }}-saml-proxy-mongo, key: user } },
              }
            - {
                name: MONGOPASSWORD,
                valueFrom: { secretKeyRef: { name: {{ .Values.app_name }}-saml-proxy-mongo, key: password } },
              }
            - { name: MONGOHOST, value: "{{ .Values.app_name }}-saml-proxy-mongo-svc" }
      volumes:
        - name: certificate-volume
          secret:
            secretName: {{ .Values.app_name }}-saml-proxy-secret
        - name: config-volume
          configMap:
          {{ if .Values.isdev }}
            name: {{ .Values.app_name }}-saml-dev-config
          {{ else }}
            name: {{ .Values.app_name }}-saml-prod-config
          {{ end }}
        