apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-saml-proxy-mongo-svc
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}-saml-proxy-mongo-svc
    app.kubernetes.io/component: server
  namespace: rse
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}-saml-proxy-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---