apiVersion: v1
kind: Service
metadata:
  name: dev-idp-{{ .Values.app_name }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dev_idp-{{ .Values.app_name }}-svc
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}-keycloak
