apiVersion: v1
kind: Service
metadata:
  name: dev_idp_{{ .Values.app_name }}_svc
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: dev_idp_{{ .Values.app_name }}_svc
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app.kubernetes.io/name: dev_idp_{{ .Values.app_name }}
