apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ Values.app_name }}-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ Values.app_name }}-nginx
  template:
    metadata:
      labels:
        app: {{ Values.app_name }}-nginx
    spec:
      containers:
        - name: {{ Values.app_name }}-nginx
          image: nginx:alpine
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              readOnly: true              
          ports:
            - containerPort: 80 
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.app_name }}-nginx-config